<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HttpGossip" Version="1.0.1" />
    <PackageReference Include="Rkd.Scalar" Version="1.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IdentityAndAccess.Identity.Application\IdentityAndAccess.Identity.Application.csproj" />
    <ProjectReference Include="..\IdentityAndAccess.Identity.Infrastructure\IdentityAndAccess.Identity.Infrastructure.csproj" />
  </ItemGroup>

</Project>
